### ISSUE TITLE
Now builds on Linux, new issue raised

### ISSUE THREAD

**Issue by Droon99-Developer** [iRath96/Minecraft-Overviewer#1]
First, I would like to thank you for getting back to me so quickly. The branch now successfully builds, however when I attempt to run it throws the following error:
```Traceback (most recent call last):
  File "/home/droon/Minecraft-Overviewer/overviewer_core/textures.py", line 72, in <module>
    from .c_overviewer import alpha_over, init_chunk_render
SystemError: initialization of c_overviewer raised unreported exception
```

**Comment by ST-Electro** [comment]
I ran into the same problem:

```
Traceback (most recent call last):
  File "/home/minecraft/raksaservu/overviewer/overviewer_core/textures.py", line 72, in <module>
    from .c_overviewer import alpha_over, init_chunk_render
SystemError: initialization of c_overviewer raised unreported exception
```

My system info:
Ubuntu Linux 18.04.2
Python3 3.6.7-1~18.04

Looking forward to fix since the master doesn't support the new 1.16 blocks (for now)

**Comment by cheide** [comment]
It seems to be a problem with the circular importing between textures.py and the init_chunk_render call, where the attempt to import overview_core.textures fails and the 'textures' pointer is left NULL. Commenting out the call to init_chunk_render in PyInit_c_overviewer gets things moving again, though I don't know if it's the _correct_ thing to do...

This was with also with Python 3.6 on Ubuntu 18.04, in case there's some Python version-specific behaviour with this circular importing.

**Comment by ST-Electro** [comment]
Took me a while to figure out where I can find "the call to init_chunk_render in PyInit_c_overviewer"
I guess its the one in /overviewer_core/src/main.c

So, if I understood you correctly, I commented out lines 70-74 from main.c
```
    /* initialize, and return if error is set */
    //if (!init_chunk_render()) {
    //    PyErr_Print();
    //    exit(1);
    //    return NULL;
    //}
```
After doing that, I rebuild the core with "python3 setup.py build" and tried to generate the map with "overviewer.py --config=overviewer.conf": Rendering was completed in normal time without errors, but the output is completely blank. I checked the images in the render output folder and they all are just background coloured.

Am I missing something or is this fix even possible to work?

**Comment by lhoffl** [comment]
Any updates here? I'm running into similar issues on Centos 8.1.1911 using Python 3.6.8

**Comment by Droon99-Developer** [comment]
Oddly it seems to work fine on my Manjaro Desktop but not on my Ubuntu server. Maybe library issues/differences?
